routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('product', \App\Http\Controllers\ProductController::class)->only(['index', 'show']);
Route::resource('article', \App\Http\Controllers\ArticleController::class)->only(['index', 'show']);

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('logs', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index'])->name('logs');

Route::get('oauth/{provider}', [\App\Http\Controllers\HomeController::class, 'oauth'])->name('oauth.auth');

Route::get('faq', function () {
    return view('faq');
})->name('faq');

Route::get('/auth/redirect/{provider}', function ($provider) {
    return Socialite::driver($provider)->redirect();
})->name('oauth.redirect');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::post('user/delete', [\App\Actions\Fortify\UpdateUserProfileInformation::class, 'delete'])->name('user-profile-information.delete');
    Route::post('user/update/email', [\App\Actions\Fortify\UpdateUserProfileInformation::class, 'updateEmail'])->name('user-profile-information-email.update');

    Route::get('my-products', [\App\Http\Controllers\ProductController::class, 'myProducts'])->name('user.products');

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/View/Components/GuestLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;

class GuestLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     *
     * @return \Illuminate\View\View
     */
    public function render()
    {
        return view('layouts.guest');
    }
}

resources/views/article.blade.php
@extends('layouts.default')
@section('content')
    <main class="article_main">
        <div class="article_breadcrumbs">
            <ul class="article_breadcrumbs_items">
                <li class="article_breadcrumbs_item">
                    <a href="{{ route('article.index') }}">Vim Blog</a>
                </li>
                <li class="article_breadcrumbs_item">
                    <span>{{ $article->title }}</span>
                </li>
            </ul>
        </div>
        <div class="article_thumb">
            <h2 class="article_thumb_title">
                {{ $article->title }}
            </h2>
            <p class="article_thumb_text">
                {!! $article->short_text !!}
            </p>
            <a href="{{ route('article.index') }}" class="article_thumb_buy">
                Buy Vimguard
            </a>
        </div>
        <div class="article_main_image">
            <img src="{{ $article->image }}" alt="Main image">
        </div>
        <div class="article_main_section">
            <div class="article_main_section_left">
                {!! $article->text !!}
                <hr>
                <div class="article_main_section_author">
                    <div class="article_main_section_author_left">
                        <p>by <b>{{ $article->author }}</b> on {{ $article->created_at }}</p>
                    </div>
                    <div class="article_main_section_author_right">
                        <a href="#" target="_blank" rel="noopener noreferrer">
                            <img src="/images/entypo-social_facebook.png" alt="a">
                        </a>
                        <a href="#" target="_blank" rel="noopener noreferrer">
                            <img src="/images/fa-brands_twitter-square.png" alt="a">
                        </a>
                        <a href="#" target="_blank" rel="noopener noreferrer">
                            <img src="/images/akar-icons_linkedin-fill.png" alt="a">
                        </a>
                        <a href="#" target="_blank" rel="noopener noreferrer">
                            <img src="/images/fa-solid_share-alt-square.png" alt="a">
                        </a>
                    </div>
                    <br>
                    <br>
                    <br>
                </div>
            </div>
        </div>
    </main>
@endsection

resources/views/blog.blade.php
@extends('layouts.default')
@section('content')
<main class="main_blog">
    <div class="main_blog_banner">
        <h4 class="main_blog_banner_title">
            Vim blog
        </h4>
        <p class="main_blog_banner_text">
            VimGuard prevents 1.5 billion cyber attacks per month. And in our free time, we love teaching the world
            about digital security, online privacy, and device performance. See all of our guides, tips, and advice
            right here.
        </p>
    </div>
    <div class="blog_articles">
        <div class="blog_articles_items">
            @foreach($articles as $article)
                <div class="blog_articles_item vim_news">
                    <a href="{{ route('article.show', ['article' => $article->slug]) }}">
                        <img src="{{ $article->image }}" alt="a" class="blog_articles_item_image">
                        <h4 class="blog_articles_item_title">
                            {{ $article->name }}
                        </h4>
                        <p class="blog_articles_item_text">
                            {!! $article->short_text !!}
                        </p>
                        <div class="blog_articles_item_infoline">
                            <span class="blog_articles_item_date">{{ $article->created_at }}</span>
                            {{--<span class="blog_articles_item_views">1024 viewes</span>--}}
                        </div>
                    </a>
                </div>
            @endforeach
        </div>
    </div>
</main>
@endsection

resources/views/buy.blade.php
@extends('layouts.default')
@section('content')
    <main class="buy_main">
        <div class="buy_main_choose">
            <div class="buy_main_choose_container">
                <h2 class="buy_main_choose_title">
                    Сhoose your level of protection
                </h2>
                <p class="buy_main_choose_available">
                    <span>Avaliable platforms: </span>
                    <img src="{{asset('images/wind.png')}}" alt="Windows">
                    <img src="{{asset('images/mac.png')}}" alt="MacOC">
                    <img src="{{asset('images/android.png')}}" alt="Android">
                    <img src="{{asset('images/apple.png')}}" alt="Apple">
                </p>
                <div class="buy_main_choose_items">

                    @foreach($products as $product)
                        <div class="buy_main_choose_item">
                            <h4 class="buy_main_choose_item_title">{{ $product->name }}</h4>
                            <p class="buy_main_choose_item_devices">one device</p>
                            <p class="buy_main_choose_item_price euro">{{ $product->price }}</p>
                            @if ($product->price == '0.00')
                                <a href="{{asset('test.exe')}}" class="buy_main_choose_item_buybutton">
                                    DOWNLOAD
                                </a>
                            @else
                                <button type="button" onclick="openBilling('{{ $product->slug }}', {{$product->price}})"
                                        class="buy_main_choose_item_buybutton">
                                    BUY NOW
                                </button>
                            @endif
                            <p class="buy_main_choose_item_undertex">
                                Price for the first year only
                            </p>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>


        <div class="confirm_popup" id="confirm-popup" style="display: none; opacity: 0;">
            <div class="confirm_popup_container">
                <ajax-form method="POST" action="{{route('api.product.store')}}" success="openSuccessful">
                    <div class="confirm_popup_container_firstline">
                        <span>
                            Credit or debit cards
                        </span>
                        <div class="confirm_popup_container_systems">
                            <img src="{{asset('images/mastercard.png')}}" alt="Master Cart">
                            <img src="{{asset('images/visa.png')}}" alt="Visa">
                        </div>
                    </div>
                    <div class="confirm_popup_container_billing">
                        <p class="confirm_popup_container_billing_title">
                            Please, tell us your billing details
                        </p>
                        <div class="confirm_popup_container_billing_inputs">
                            <input type="hidden" name="product.slug" id="product-slug">
                            <input type="text" name="user.name" id="billing-name" placeholder="First name(s):">
                            <input type="text" name="user.lastname" id="billing-lastname" placeholder="Last name:">
                            <input type="email" name="user.email" id="billing-email" placeholder="E-mail:">
                            <input type="tel" name="user.phone" id="billing-phone" placeholder="Phone number:">
                        </div>
                    </div>
                    <p class="confirm_popup_container_info">
                    </p>
                    <div class="confirm_popup_container_cart">
                        <input type="text" mask="0000 0000 0000 0000" mask-reverse="true" name="card.number"
                               id="cart-number" placeholder="Card number:">
                        <input type="text" mask="00/00" name="card.date" id="billing-date" placeholder="MM/YY">
                        <input type="text" mask="000" name="card.cvc" id="billing-cvc" placeholder="CVC">
                    </div>
                    <p data-error class="confirm_popup_container_error" style="text-align: center">
                    </p>
                    <p class="confirm_popup_container_price">
                <span class="confirm_popup_container_price_text">
                    Total price:
                </span>
                        <span class="confirm_popup_container_price_num">
                    <b id="total-sum"></b> <sub>€</sub>
                </span>
                    </p>
                    <button type="submit" style="margin-left: auto;margin-right: auto;"
                            class="confirm_popup_container_button">
                        Confirm
                    </button>
                </ajax-form>
            </div>
        </div>

        <div class="confirm_popup" id="saccefull-payment">
            <div class="saccefull_payment">
                <h3 class="saccefull_payment_title">
                    Payment Saccefull
                </h3>
                <div class="saccefull_payment_container">
                    <h4 class="saccefull_payment_container_ft">
                        Thank you for purchasing VimGuard!
                    </h4>
                    <p class="saccefull_payment_container_text">
                        To manage security across all your devices from anywhere via the Web,
                        you can create a Vim account. This allows you to check each device's security
                        &amp; license status, adjust key security settings - plus access special offers and
                        download free Vim products.
                        <br>
                        Vim also gives you easy access to technical support.
                        To avoid any conflicts between programs, you may need to close some
                        active applications and uninstall third-party solutions with antivirus
                        or similar functionality.
                    </p>
                    <h4 class="saccefull_payment_container_st">
                        Installing the program
                    </h4>
                    <p class="saccefull_payment_container_text">
                        To install VimGuard, download the installation file and run it on your pc.
                    </p>
                    <a href="#" class="saccefull_payment_container_link">Download VimGuard</a>
                    <h4 class="saccefull_payment_container_st">
                        Activate the program
                    </h4>
                    <p class="saccefull_payment_container_text">
                        To activate it, open VimGuard on your PC. Go to the Settings menu,
                        then go to the License tab, click the Activate product button.
                        In the field that appears, paste the key that you can copy in your
                        personal account
                    </p>
                    <a href="{{route('user.products')}}" class="saccefull_payment_container_link">{{route('user.products')}}</a>
                    <a href="{{route('user.products')}}" class="saccefull_payment_container_button">
                        go to activate
                    </a>
                </div>
            </div>
        </div>

        @include('components.module.blog')
    </main>
@endsection

resources/views/dashboard.blade.php
@extends('layouts.admin')
@section('content')
    <div class="main_page_first_line">
        <h2 class="main_page_first_line_title">
            Welcome to Vim
        </h2>
        <p class="main_page_first_line_text">
            You're logged in as {{Auth::user()->email}}
        </p>
    </div>
    <div class="main_page_menu">
        <ul class="main_page_menu_items">
            <li class="main_page_menu_item">
                <img src="{{asset('images/adminpanel/folder1212.png')}}" alt="Folder" class="main_page_menu_item_img">
                <div class="main_page_menu_item_container">
                    <a href="{{route('user.products')}}" class="main_page_menu_item_container_link">My products</a>
                    <p class="main_page_menu_item_container_info">
                        View and manage the subscriptions you've bought.
                    </p>
                </div>
            </li>
            <li class="main_page_menu_item">
                <img src="{{asset('images/adminpanel/monitor124.png')}}" alt="Monitor" class="main_page_menu_item_img">
                <div class="main_page_menu_item_container">
                    <a href="{{route('profile.show')}}" class="main_page_menu_item_container_link">Account settings</a>
                    <p class="main_page_menu_item_container_info">
                        View and manage your account details, change your password, and more.
                    </p>
                </div>
            </li>
            <li class="main_page_menu_item">
                <img src="{{asset('images/adminpanel/chat4550.png')}}" alt="Chat" class="main_page_menu_item_img">
                <div class="main_page_menu_item_container">
                    <a href="{{route('faq')}}" class="main_page_menu_item_container_link">How to install and
                        activate</a>
                    <p class="main_page_menu_item_container_info">
                        Download, install, and activate your product.
                    </p>
                </div>
            </li>
            {{--            <li class="main_page_menu_item">--}}
            {{--                <img src="{{asset('images/adminpanel/cards765.png')}}" alt="Cards" class="main_page_menu_item_img">--}}
            {{--                <div class="main_page_menu_item_container">--}}
            {{--                    <a href="#" class="main_page_menu_item_container_link">Get refund</a>--}}
            {{--                    <p class="main_page_menu_item_container_info">--}}
            {{--                        Request a refund during the 30-day refund period.--}}
            {{--                    </p>--}}
            {{--                </div>--}}
            {{--            </li>--}}
        </ul>
    </div>
@endsection

resources/views/faq.blade.php
@extends('layouts.admin')
@section('content')
    <div class="main_admin_questions_container">
        <div class="main_admin_questions_chapter">
            <div class="main_admin_questions_chapter_header">
                <p class="main_admin_questions_chapter_header_text">
                    Installation and Activation
                </p>
            </div>
            <div class="main_admin_questions_items">
                <div class="main_admin_questions_item">
                    <h5 class="main_admin_questions_question">
                        <span>Download and install you Vim product</span>
                    </h5>
                    <p class="main_admin_questions_answer">
                        <span>To download and install your Avast product:</span>
                        <span>1. Click the button below to open our download and installation help page:</span>
                        <button type="button" class="main_admin_questions_answer_btn">GET Vimguard</button>
                        <span>2. Use the Choose your product drop-down menu to select your purchased product.</span>
                        <span>3. Use the Choose your platform drop-down menu to select your platform.</span>
                        <span>4. Click See Installation Instructions, then follow the on-screen steps.</span>
                        <span>Your Vim product is now installed on your device. If you have not yet activated your subscription, refer the the next sections in this article for information about locating your activation code and activating your Vim product.</span>
                    </p>
                </div>
                <div class="main_admin_questions_item">
                    <h5 class="main_admin_questions_question">
                        <span>Locate your activation code</span>
                    </h5>
                    <p class="main_admin_questions_answer">
                        <span>You can find your activation code in one of the following locations:</span>
                        <span class="marker">The <a href="#">Vim Account</a> that is linked to the email address you provided during the subscription purchase.</span>
                        <span class="marker">The <b>order confirmation email&nbsp;</b> that you received after purchase (usually from refund@vimguard.com).</span>
                        <span class="marker">The <b>activation card&nbsp;</b> that was included with your purchase in an Vim box or plastic case.</span>
                        <span class="marker"><b>Another Vim product&nbsp;</b> that you have already activated using the same activation code.</span>
                        <span>For detailed instructions on locating your activation code, refer to the following article:</span>
                        <span class="marker"><a href="#">Locating your Vim activation code</a></span>
                        <span>For detailed instructions on retrieving an activation code from your Vim Account, refer to the following article:</span>
                        <span class="marker">Retrieving an activation code from your Vim Account</span>
                    </p>
                </div>
                <div class="main_admin_questions_item">
                    <h5 class="main_admin_questions_question">
                        <span>Activate your Vim product</span>
                    </h5>
                    <p class="main_admin_questions_answer">
                        <span>You can find your activation code in one of the following locations:</span>
                        <span>1. Locate your activation code. This is included in your order confirmation email. For detailed instructions, refer to the following article:</span>
                        <span class="marker"><a href="#">Locating your Vim activation code</a></span>
                        <span>2. Double-click the Vim Internet Security icon on your Windows desktop to open the application.</span>
                        <span>For alternative options to open Vim Internet Security, refer to the following article:</span>
                        <span class="marker"><a href="#">Opening Vim applications</a></span>
                        <span>3. Select <b>☰ Menu ▸ Enter activation code.</b></span>
                        <span>4. Type or paste your <b>activation code</b> (including hyphens) into the text box, then click <b>Enter</b>.</span>
                        <span>5. If your activation code is valid for <b>multiple products</b>, untick the box next to any products that you <b>do not</b> want to install and activate.</span>
                        <span>Click <b>Activate & install</b> to confirm activation and installation of all selected products.</span>
                        <span>Your Vim Internet Security subscription is now active. If activation is unsuccessful, refer to the Still need help? section in this article.</span>
                    </p>
                </div>
                <div class="main_admin_questions_item">
                    <h5 class="main_admin_questions_question">
                        <span>Transfer your subscription to another device</span>
                    </h5>
                    <p class="main_admin_questions_answer">
                        <span>To learn how to transfer an Vim subscription from one device to another, refer to the following article:</span>
                        <span class="marker"><a href="#">Transferring an Vim subscription to another device</a></span>
                    </p>
                </div>
            </div>
        </div>
        <div class="main_admin_questions_chapter">
            <div class="main_admin_questions_chapter_header">
                <p class="main_admin_questions_chapter_header_text">
                    Troubleshooting
                </p>
            </div>
            <div class="main_admin_questions_items">
                <div class="main_admin_questions_item">
                    <h5 class="main_admin_questions_question">
                        <span>Which Vim product(s) did I purchase?</span>
                    </h5>
                    <p class="main_admin_questions_answer">
                        <span>Some Avast subscriptions are valid for multiple products, and some are valid for just one product. You can verify what is included in your Avast subscription using one of the methods below:</span>
                        <span class="marker"><b>Vim Account</b>: Sign in to the Vim Account that is linked to the email address you provided at checkout, then click the Subscriptions tile. The valid platforms and products for each subscription are listed under Install on your devices.</span>
                        <span class="marker"><b>Order confirmation email</b>: Locate the order confirmation email that you received after purchase (usually from refund@vimguard.com). The valid platforms and products are listed under <b>Your products</b>.
                            </span>
                    </p>
                </div>
                <div class="main_admin_questions_item">
                    <h5 class="main_admin_questions_question">
                        <span>What if installation fails?</span>
                    </h5>
                    <p class="main_admin_questions_answer">
                        <span>Before following the installation steps in this article, ensure that your PC is properly prepared for installation. For instructions, refer to the following article:</span>
                        <span class="marker"><a href="#">Preparing your PC for installation of Vim software</a></span>
                        <span>If this does not resolve the issue, try installing your Vim product using one of our detailed installation articles.</span>
                        <span>If installation continues to fail, you can click the link below to open the Vim <b>Technical Support</b> form. After you submit the request, an Vim Support agent will contact you to help resolve the issue.</span>
                        <span class="marker"><a href="#">Contact Vim Support</a></span>
                    </p>
                </div>
                <div class="main_admin_questions_item">
                    <h5 class="main_admin_questions_question">
                        <span>What if activation is unsuccessful?</span>
                    </h5>
                    <p class="main_admin_questions_answer">
                        <span>Review the information below, which explains how to resolve some of the most common activation issues.</span>
                        <span>Your activation method:</span>
                        <span class="method"><a href="#">VIM ACCOUNT</a><a href="#">ACTIVATION CODE</a></span>
                        <span>If your Vim product displays an <b>expiration message</b>, refer to the following section of this article to ensure your product is properly activated:</span>
                        <span class="marker">Activate your Vim product</span>
                        <span>Ensure you are correctly entering your activation code (including hyphens). Refer to the following section of this article for more information about locating your activation code:</span>
                        <span class="marker"><a href="#">Locate your activation code</a></span>
                        <span>If you see an error message during activation, refer to the following article for advice:</span>
                        <span class="marker"><a href="#">Troubleshooting common activation error messages</a></span>
                        <span>If you are still unable to activate your subscription, you can click the link below to open the Vim Technical Support form. After you submit the request, an Vim Support agent will contact you to help resolve the issue.</span>
                        <span class="marker"><a href="#">Contact Vim Support</a></span>
                    </p>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/policy.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $policy !!}
            </div>
        </div>
    </div>
</x-guest-layout>

resources/views/terms.blade.php
<x-guest-layout>
    <div class="pt-4 bg-gray-100">
        <div class="min-h-screen flex flex-col items-center pt-6 sm:pt-0">
            <div>
                <x-jet-authentication-card-logo />
            </div>

            <div class="w-full sm:max-w-2xl mt-6 p-6 bg-white shadow-md overflow-hidden sm:rounded-lg prose">
                {!! $terms !!}
            </div>
        </div>
    </div>
</x-guest-layout>