routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('product', \App\Http\Controllers\ProductController::class)->only(['index', 'show']);
Route::resource('article', \App\Http\Controllers\ArticleController::class)->only(['index', 'show']);

Route::get('/', [\App\Http\Controllers\HomeController::class, 'index'])->name('home');

Route::get('logs', [\Rap2hpoutre\LaravelLogViewer\LogViewerController::class, 'index'])->name('logs');

Route::get('oauth/{provider}', [\App\Http\Controllers\HomeController::class, 'oauth'])->name('oauth.auth');

Route::get('faq', function () {
    return view('faq');
})->name('faq');

Route::get('/auth/redirect/{provider}', function ($provider) {
    return Socialite::driver($provider)->redirect();
})->name('oauth.redirect');

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::post('user/delete', [\App\Actions\Fortify\UpdateUserProfileInformation::class, 'delete'])->name('user-profile-information.delete');
    Route::post('user/update/email', [\App\Actions\Fortify\UpdateUserProfileInformation::class, 'updateEmail'])->name('user-profile-information-email.update');

    Route::get('my-products', [\App\Http\Controllers\ProductController::class, 'myProducts'])->name('user.products');

    Route::get('/dashboard', function () {
        return view('dashboard');
    })->name('dashboard');
});

app/Models/Product.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\BelongsToMany;
use Illuminate\Database\Eloquent\Relations\HasMany;

class Product extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'm_id',
        'category_id',
        'name',
        'slug',
        'details',
        'logo',
        'price',
        'is_best',
        'tpl'
    ];

    static public $FREE_SLUG = 'free-antivirus';
    static public $PREMIUM_SLUG = 'premium-security';
    static public $ULTIMATE_SLUG = 'ultimate';

    public function platforms(): BelongsToMany
    {
        return $this->belongsToMany(
            Platform::class,
            'product_has_platform',
            'product_id',
            'platform_id'
        );
    }

    public function category(): BelongsTo
    {
        return $this->belongsTo(Category::class);
    }

    public static function getFreeProduct()
    {
        return self::query()->where('slug', self::$FREE_SLUG)->first();
    }

    public static function getPremiumProduct()
    {
        return self::query()->where('slug', self::$PREMIUM_SLUG)->first();
    }

    public static function getUltimateProduct()
    {
        return self::query()->where('slug', self::$ULTIMATE_SLUG)->first();
    }

    public function productKeys(): HasMany
    {
        return $this->hasMany(ProductKey::class);
    }
}

app/Http/Controllers/Api/ProductController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use App\Http\Requests\Product\ProductInvoiceRequest;
use App\Http\Resources\Product\ProductKeyResource;
use App\Models\Product;
use App\Models\User;
use App\Services\Megaplan\Extensions\MegaplanInvoiceExtension;
use App\Services\Megaplan\MegaplanApiService;
use App\Services\PaymentService;
use App\Services\ProductKeyService;
use Ramsey\Uuid\Uuid;
use Symfony\Component\HttpKernel\Exception\UnprocessableEntityHttpException;

class ProductController extends Controller
{
    /**
     * Product's invoice request.
     *
     * @param ProductInvoiceRequest $request
     * @param ProductKeyService $productKeyService
     * @param PaymentService $paymentService
     * @param MegaplanApiService $megaplanApiService
     *
     * @return ProductKeyResource
     */
    public function store(ProductInvoiceRequest $request,
                          ProductKeyService $productKeyService,
                          PaymentService $paymentService,
                          MegaplanApiService $megaplanApiService): ProductKeyResource
    {
        /** @var User $user */
        $user = User::firstOrCreate([
            'email' => $request->client()['email']
        ], array_merge($request->client(), ['password' => \Str::random(), 'uuid' => Uuid::uuid4()]));

        $megaplanApiService->Client->CreateOrUpdate($user);

        /** @var Product $product */
        $product = Product::whereSlug($request->product())->firstOrFail();

        /* Trying to invoice product amount from user's card. Card authorization made with request's rule. */
        if (!$paymentService->invoice($request->card()['number'], $request->card()['date'], $request->card()['cvc'], $product->price)) {
            throw new UnprocessableEntityHttpException(trans('validation.payment.card.invoice'));
        }

        // Create product key
        $productKey = $productKeyService->createProductKey($product, $user);
        // Create invoice
//        $megaplanApiService->Invoice->CreateOrUpdateWithStatus($productKey, MegaplanInvoiceExtension::$STATUS_TEMPLATE);
//        // Add product to invoice
//        $megaplanApiService->InvoiceRow->CreateOrUpdate($productKey);
//
//        // Create deal
//        $deal = $megaplanApiService->Deal->CreateOrUpdate($productKey);
//        // Update invoice with status and deal
//        $megaplanApiService->Invoice->CreateOrUpdateWithStatus($productKey, MegaplanInvoiceExtension::$STATUS_CREATED, $deal['Id']);
//        $megaplanApiService->Invoice->CreateOrUpdateWithStatus($productKey, MegaplanInvoiceExtension::$STATUS_PAYED, $deal['Id']);

        return ProductKeyResource::make($productKey);
    }
}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Models\Product;
use App\Models\User;
use Illuminate\Contracts\Foundation\Application;
use Illuminate\Contracts\View\Factory;
use Illuminate\Contracts\View\View;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return Application|Factory|View
     */
    public function index()
    {
        return view('buy', [
            'products' => Product::all(),
        ]);
    }
//
//    /**
//     * Show the form for creating a new resource.
//     *
//     * @return \Illuminate\Http\Response
//     */
//    public function create()
//    {
//        //
//    }
//
//    /**
//     * Store a newly created resource in storage.
//     *
//     * @param  \Illuminate\Http\Request  $request
//     * @return \Illuminate\Http\Response
//     */
//    public function store(Request $request)
//    {
//        //
//    }

    /**
     * Display the specified resource.
     *
     * @param string $slug
     * @return Application|Factory|View
     */
    public function show(string $slug)
    {
        $product = Product::whereSlug($slug)->firstOrFail();
        return view($product->tpl, [
            'product' => $product
        ]);
    }

//    /**
//     * Show the form for editing the specified resource.
//     *
//     * @param  int  $id
//     * @return \Illuminate\Http\Response
//     */
//    public function edit($id)
//    {
//        //
//    }
//
//    /**
//     * Update the specified resource in storage.
//     *
//     * @param  \Illuminate\Http\Request  $request
//     * @param  int  $id
//     * @return \Illuminate\Http\Response
//     */
//    public function update(Request $request, $id)
//    {
//        //
//    }
//
//    /**
//     * Remove the specified resource from storage.
//     *
//     * @param  int  $id
//     * @return \Illuminate\Http\Response
//     */
//    public function destroy($id)
//    {
//        //
//    }

    public function myProducts()
    {
        /** @var User $user */
        $user = auth()->user();
        return view('products.my-products', [
            'productKeys' => $user->productKeys()->with('product.platforms')->get()
        ]);
    }
}

resources/views/products/free.blade.php
@extends('layouts.default')
@section('content')
    <main class="main">
        <div class="product_banner">
            <div class="product_banner_left">
                <img src="{{asset('images/laptop.png')}}" alt="Laptop">
            </div>
            <div class="product_banner_right">
                <div class="product_banner_title">
                    {{ $product->name }}
                </div>
                <p class="product_banner_text">
                    {!! $product->description !!}
                </p>
                <div class="product_banner_trust">
                    <img src="{{asset('images/checkvim.png')}}" alt="Check">
                    <p class="product_banner_trust_text">
                        No viruses and adware
                    </p>
                </div>
                <a href="{{asset('test.exe')}}" class="product_banner_button">
                    Download
                </a>
                <p class="product_banner_also">
                    Also available for: <span>Android</span>, <span>iOS</span>, <span>Mac</span>
                </p>
            </div>
        </div>
        <div class="product_secvices">
            <div class="product_secvices_item">
                <div class="product_secvices_item_image">
                    <img src="{{asset('images/serv/adblock.png')}}" alt="Ad blocking">
                </div>
                <div class="product_secvices_item_about">
                    <h4 class="product_secvices_item_about_title">Ad blocking</h4>
                    <p class="product_secvices_item_about_text">
                        VimGuard ad filter blocks all kinds of ads.
                        Pop-ups, video ads, banners and such — they will all go away.
                        Due to unnoticeable background filtering and cosmetic processing,
                        all you will see is clean pages with the content you came for.
                    </p>
                </div>
            </div>
            <div class="product_secvices_item">
                <div class="product_secvices_item_image">
                    <img src="{{asset('images/serv/browser.png')}}" alt="Safe web surfing">
                </div>
                <div class="product_secvices_item_about">
                    <h4 class="product_secvices_item_about_title">Safe web surfing</h4>
                    <p class="product_secvices_item_about_text">
                        Protection from phishing and hazardous websites
                        and malvertising (malicious ads). VimGuard
                        checks every page against our database for any malicious
                        content and blocks requests from potentially dangerous ones.
                    </p>
                </div>
            </div>
            <div class="product_secvices_item">
                <div class="product_secvices_item_image">
                    <img src="{{asset('images/serv/privacyprot.png')}}" alt="Privacy protection">
                </div>
                <div class="product_secvices_item_about">
                    <h4 class="product_secvices_item_about_title">Privacy protection</h4>
                    <p class="product_secvices_item_about_text">
                        VimGuard fights against all trackers and analytical systems
                        that spy on you. The program blocks third-party cookies,
                        can hide your IP address, and provides an abundance of other
                        features to protect your personal data.
                    </p>
                </div>
            </div>
            <div class="product_secvices_item">
                <div class="product_secvices_item_image">
                    <img src="{{asset('images/serv/paternalcontrol.png')}}" alt="Parental control">
                </div>
                <div class="product_secvices_item_about">
                    <h4 class="product_secvices_item_about_title">Parental control</h4>
                    <p class="product_secvices_item_about_text">
                        VimGuard protects your children online. It blocks access
                        to inappropriate websites, removes obscene materials from
                        search results, and provides parents with a customizable
                        blacklist to tailor the safest web experience for their kids.
                    </p>
                </div>
            </div>
            <div class="product_secvices_item">
                <div class="product_secvices_item_image">
                    <img src="{{asset('images/serv/group.png')}}" alt="Protect your data">
                </div>
                <div class="product_secvices_item_about">
                    <h4 class="product_secvices_item_about_title">Protect your data</h4>
                    <p class="product_secvices_item_about_text">
                        Everything on the web nowadays tries to steal your data.
                        AdGuard has a dedicated module to prevent that from happening.
                    </p>
                </div>
            </div>
            <div class="product_secvices_item">
                <div class="product_secvices_item_image">
                    <img src="{{asset('images/serv/hacker.png')}}" alt="Disguise yourself online">
                </div>
                <div class="product_secvices_item_about">
                    <h4 class="product_secvices_item_about_title">Disguise yourself online</h4>
                    <p class="product_secvices_item_about_text">
                        Instead of simply hiding your online profile,
                        you can change it to appear as someone else and
                        browse anonymously.
                    </p>
                </div>
            </div>
        </div>
        <div class="laureats">
            <div class="laureats_left">
                <img src="{{asset('images/laureatsimg.png')}}" alt="Laureats">
            </div>
            <div class="laureats_right">
                <div class="laureats_item">
                    <div class="laureats_item_left">
                        <img src="{{asset('images/toprated.png')}}" alt="Top Rated best">
                    </div>
                    <div class="laureats_item_righ">
                        <p class="laureats_item_year">
                            2021
                        </p>
                        <h5 class="laureats_item_title">
                            Top Rated best
                        </h5>
                    </div>
                </div>
                <div class="laureats_item">
                    <div class="laureats_item_left">
                        <img src="{{asset('images/homeadvisor.png')}}" alt="Top Rated product">
                    </div>
                    <div class="laureats_item_righ">
                        <p class="laureats_item_year">
                            2020
                        </p>
                        <h5 class="laureats_item_title">
                            Top Rated product
                        </h5>
                    </div>
                </div>
                <div class="laureats_item">
                    <div class="laureats_item_left">
                        <img src="{{asset('images/greatnonprof.png')}}" alt="Top Rated product">
                    </div>
                    <div class="laureats_item_righ">
                        <p class="laureats_item_year">
                            2020
                        </p>
                        <h5 class="laureats_item_title">
                            Top Rated product
                        </h5>
                    </div>
                </div>
            </div>
        </div>
        <div class="product_comeon">
            <p class="product_comeon_text">
                Install VimGuard for Windows and see the Internet as it was supposed to be — clean and safe.
            </p>
        </div>
        <div class="product_faq" style="margin-top: 3%;">
            <h3 class="product_faq_title">
                FAQ
            </h3>
            <div class="product_faq_container">
                <div class="product_faq_item">
                    <h5 class="product_faq_question">
                        <span>How do I install VimGuard?</span>
                    </h5>
                    <p class="product_faq_answer">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Earum, ratione cupiditate eveniet similique quibusdam doloribus
                        odio quam corporis molestiae ex! Iure, sapiente aliquam!
                        Accusantium, exercitationem soluta hic tempora pariatur eligendi.
                    </p>
                </div>
                <div class="product_faq_item">
                    <h5 class="product_faq_question">
                        <span>Why is VimGuard better than other apps?</span>
                    </h5>
                    <p class="product_faq_answer">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Earum, ratione cupiditate eveniet similique quibusdam doloribus
                        odio quam corporis molestiae ex! Iure, sapiente aliquam!
                        Accusantium, exercitationem soluta hic tempora pariatur eligendi.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Earum, ratione cupiditate eveniet similique quibusdam doloribus
                        odio quam corporis molestiae ex! Iure, sapiente aliquam!
                        Accusantium, exercitationem soluta hic tempora pariatur eligendi.
                    </p>
                </div>
                <div class="product_faq_item">
                    <h5 class="product_faq_question">
                        <span>What are the main features of VimGuard for Windows?</span>
                    </h5>
                    <p class="product_faq_answer">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Earum, ratione cupiditate eveniet similique quibusdam doloribus
                        odio quam corporis molestiae ex! Iure, sapiente aliquam!
                        Accusantium, exercitationem soluta hic tempora pariatur eligendi.
                    </p>
                </div>
                <div class="product_faq_item">
                    <h5 class="product_faq_question">
                        <span>What if I have questions? Do you have a support service?</span>
                    </h5>
                    <p class="product_faq_answer">
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Earum, ratione cupiditate eveniet similique quibusdam doloribus
                        odio quam corporis molestiae ex! Iure, sapiente aliquam!
                        Accusantium, exercitationem soluta hic tempora pariatur eligendi.
                        Lorem ipsum dolor sit amet consectetur adipisicing elit.
                        Earum, ratione cupiditate eveniet similique quibusdam doloribus
                        odio quam corporis molestiae ex! Iure, sapiente aliquam!
                        Accusantium, exercitationem soluta hic tempora pariatur eligendi.
                    </p>
                </div>
            </div>
        </div>
        @include('components.module.blog')
    </main>
@endsection

resources/views/products/my-products.blade.php
@extends('layouts.admin')
@section('content')
    <main class="main_admin">
        <div class="main_page_first_line">
            <h2 class="main_page_first_line_title">
                My products
            </h2>
            <p class="main_page_first_line_text">
                Only paid subscriptions will appear here. To see mobile subscriptions, just log into your mobile app.
            </p>
        </div>
        @if($productKeys->count() === 0)
            <div class="main_page_product_empty">
                <img src="{{asset('images/adminpanel/computer4110.png')}}" alt="Computer and server"
                     class="main_page_product_empty_img">
                <p class="main_page_product_empty_text">No products here, yet.</p>
                <a href="{{route('product.index')}}" type="button" class="main_page_product_empty_btn">get now</a>
            </div>
        @else
            <div class="main_page_product_list">
                <div class="main_page_product_list_header">
                    <div class="main_page_product_list_header_item product">Product</div>
                    <div class="main_page_product_list_header_item devices">Devices</div>
                    <div class="main_page_product_list_header_item validity">Validity</div>
                    <div class="main_page_product_list_header_item price">Price</div>
                </div>
                <div class="main_page_product_list_main">
                    @foreach($productKeys as $productKey)
                        <div class="main_page_product_list_container">
                            <div class="main_page_product_list_container_item product">
                                <input type="checkbox" class="product_list_item_checkbox"
                                       id="product-{{$productKey->id}}">
                                <a
                                    data-toggle="collapse" href="#key-collapse-{{$productKey->id}}" role="button"
                                    aria-expanded="false" aria-controls="collapseExample"
                                    class="product_list_item_name d-flex flex-row">
                                    <span>{{$productKey->product->name}}</span>
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24"
                                         fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"
                                         stroke-linejoin="round" class="feather feather-chevron-down mt-2">
                                        <polyline points="6 9 12 15 18 9"></polyline>
                                    </svg>
                                </a>
                            </div>
                            <div class="main_page_product_list_container_item devices"
                                 style="white-space:nowrap; text-overflow: ellipsis;">
                                {{implode(', ', $productKey->product->platforms->pluck('name')->toArray())}}
                            </div>
                            <div class="main_page_product_list_container_item validity">
                                {{$productKey->created_at->format('d.m.Y')}}
                                - {{$productKey->created_at->addYear()->format('d.m.Y')}}
                            </div>
                        </div>
                        <div class="key_container collapse" id="key-collapse-{{$productKey->id}}">
                            <span
                                class="key_title">Your license key for {{$productKey->product->name}}: </span>{{$productKey->key}}
                        </div>
                    @endforeach
                </div>
                <div class="main_page_product_list_footer">
                    <button type="button" class="main_page_product_list_footer_btn disabled" disabled>download</button>
                </div>
            </div>
        @endif
    </main>
@endsection